spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://34.244.212.36:3306/emsp?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  hibernate:
    dialect:
      storage_engine: innodb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

  springfox:
    documentation:
      enabled: true
      title: "eMSP Account Token Service API"
      description: "Spring Boot RESTful API for Account Token Management"
      version: "1.0.0"
      contact:
        name: "Your Name"
        url: "https://your-website.com"
        email: "your-email@example.com"

  server:
    port: 8080
  logging:
    level:
      root: DEBUG
      com.baomidou.mybatisplus: debug
      org.mybatis: debug
      com.zaxxer.hikari: debug
      org.springframework.jdbc: debug
#logging:
#  level:
#    root: info





#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-handlers-package: com.yzy.config
#  map-underscore-to-camel-case: true
#  default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  mapper-locations: classpath:mappers/*.xml我想我一开始可能弄错了需求了，我们的需求是  要构建一个读取confluence 的agent ，这个agent 可以向人一样分析页面，首先页面正文说明了这个页面的具体内容，表格里记录了一些数据，我们要从正文里知道这个页面的业务内容是什么，根据正文内容我们可以判断哪些表格或表格里的哪些内容是我们关心的，下边我以实际页面举例：
1 foss页面：正文里说明了这个页面记录的是什么内容，表格里记录的是汇总信息，那agent就可以判断只需要从汇总表里拿到我关心的业务线的内容即可
2 GRAS 页面 ：正文记录了3个指标的业务含义，而下边的tap 页里记录的各个日期的不同指标下的一些统计数据，这个页面只分析表格、或只分析正文都不行，要按结构顺序相互呼应才能理解我们需要哪些数据、或表格里的数据代表什么
而我们要做的agent 就是要想人一样能理解页面内容，并安装我们的要求去抽取汇总数据，例如只关心我自己的Service Line（Data Assets&Provisioning Tech）和指定app 的内容

