name: CI/CD Pipeline for eMSP Account & Token Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 设置 Java 环境
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    # 使用 Maven 构建项目，跳过测试
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # 运行单元测试
    - name: Run tests
      run: mvn test

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t emsp-account-token-service .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v2

    # 登录到阿里云镜像仓库
    - name: Login to Alibaba Cloud ACR
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
      run: |
        # 登录到阿里云镜像仓库
        echo $ALIYUN_ACCESS_KEY_SECRET | docker login --username $ALIYUN_ACCESS_KEY_ID --password-stdin $ALIYUN_REGISTRY

    # 推送 Docker 镜像到阿里云镜像仓库
    - name: Push Docker image to Alibaba Cloud ACR
      env:
        ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
        ALIYUN_REPOSITORY: ${{ secrets.ALIYUN_REPOSITORY }}
      run: |
        docker tag emsp-account-token-service:latest $ALIYUN_REGISTRY/$ALIYUN_REPOSITORY:latest
        docker push $ALIYUN_REGISTRY/$ALIYUN_REPOSITORY:latest
