name: Docker-Image-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Move JAR to .github/workflows
        run: |
          mkdir -p .github/workflows
          mv target/*.jar .github/workflows/

      - name: Log in to Aliyun Docker Registry
        env:
          ALIYUN_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          ALIYUN_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ALIYUN_DOCKER_URL: ${{ secrets.DOCKER_LOGIN_URL }}
        run: |
          echo "${ALIYUN_DOCKER_PASSWORD}" | docker login "${ALIYUN_DOCKER_URL}" --username "${ALIYUN_DOCKER_USERNAME}" --password-stdin

      - name: Remove old Docker images
        run: |
          docker images --format '{{.Repository}}:{{.Tag}}' | grep 'crpi-9m1xqmjsfr2dw5sp.ap-northeast-1.personal.cr.aliyuncs.com/emsp-service/yzy_emsp' | xargs -I {} docker rmi -f {}

      - name: Build Docker image
        run: docker build -f .github/workflows/dockerfile -t emsp-account-token-service .github/workflows/

      - name: Tag Docker image
        run: docker tag emsp-account-token-service:latest crpi-9m1xqmjsfr2dw5sp.ap-northeast-1.personal.cr.aliyuncs.com/emsp-service/yzy_emsp:latest

      - name: Push Docker image to Aliyun registry
        run: docker push crpi-9m1xqmjsfr2dw5sp.ap-northeast-1.personal.cr.aliyuncs.com/emsp-service/yzy_emsp:latest

      # 设置 AWS CLI
      - name: Set up AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      # 复制 SSH 私钥用于 SSH 连接
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      # 使用 SSH 连接到 EC2 实例并执行命令
      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_INSTANCE_IP }} <<EOF
          # 更新系统          

            # Stop and remove old container
            sudo docker ps -q -f "name=emsp-account-token-service-c" | xargs -r sudo docker stop
            sudo docker ps -aq -f "name=emsp-account-token-service-c" | xargs -r sudo docker rm

            # Remove old Docker images
            sudo docker image prune -a -f
          
            # Remove the specific Docker image
            sudo docker rmi -f emsp-account-token-service

            # Pull the new Docker image
            sudo docker pull emsp-account-token-service

            # Run the new container
            sudo docker run -d --name emsp-account-token-service-c--restart unless-stopped -p 8080:8080 emsp-account-token-service:latest
          EOF

