# 使用 MySQL 官方镜像
FROM mysql:5.7

# 设置工作目录
WORKDIR /app

# 设置 MySQL 环境变量
ENV MYSQL_ROOT_PASSWORD=root_emsp!emsp@
ENV MYSQL_DATABASE=emsp
ENV MYSQL_USER=emsp
ENV MYSQL_PASSWORD=emsp

# 将 db 目录下的 SQL 文件复制到 MySQL 初始化目录
COPY ../../db /docker-entrypoint-initdb.d/

# 将从 Maven 构建的 JAR 文件复制到容器
COPY emsp-service-1.0.0.jar /app/emsp-service-1.0.0.jar

# 安装 JDK 8，确保容器中可以运行 Java 应用
RUN apt-get update && apt-get install -y openjdk-8-jdk

# 暴露 MySQL 端口
EXPOSE 3306

# 暴露 Java 应用端口
EXPOSE 8080

# 启动 MySQL 和 Java 应用服务
CMD service mysql start && java -jar /app/emsp-service-1.0.0.jar
