FROM ubuntu:20.04

WORKDIR /app

COPY emsp-service-1.0.0.jar /app/emsp-service-1.0.0.jar

RUN apt-get update && apt-get install -y openjdk-8-jdk

EXPOSE 8080

CMD  java -jar /app/emsp-service-1.0.0.jar
